### ISSUE TITLE
为什么会有黑边？

### ISSUE THREAD

**Issue by StrollStars** [LionelJouin/PiP-Tool#3]
框选的小窗口，会在右边和底边出现大块黑边，请问这个可以去掉吗？

**Comment by LionelJouin** [comment]
Hello, Can you be more specific ? Can you post screenshot of the small window selected with the large black border on the right and bottom.

**Comment by sickneet** [comment]
> Hello, Can you be more specific ? Can you post screenshot of the small window selected with the large black border on the right and bottom.

just like this.
![image](https://user-images.githubusercontent.com/30150112/47793655-beef9400-dd59-11e8-9fcb-8f2d95617fd5.png)
![image](https://user-images.githubusercontent.com/30150112/47793677-c7e06580-dd59-11e8-8619-e5975fa7ea9b.png)

**Comment by sickneet** [comment]
> Hello, Can you be more specific ? Can you post screenshot of the small window selected with the large black border on the right and bottom.

sometimes it also has black border on the top,and the picture is just too small,
![image](https://user-images.githubusercontent.com/30150112/47794555-a97b6980-dd5b-11e8-99c1-9b4b128ab61b.png)

**Comment by LionelJouin** [comment]
Ok, thanks, I see, it's a bug, I will try to fix it. 
Can you tell me what are your "Scale and layout" values in Display settings on Windows ?

I never encounter this bug before, I have tested on:
- A laptop with 1920x1080 and scale: 100%
- Another laptop with 1920x1080 and scale: 125%
- And a surface pro 4

**Comment by sickneet** [comment]
> Ok, thanks, I see, it's a bug, I will try to fix it.
> Can you tell me what are your "Scale and layout" values in Display settings on Windows ?
> 
> I never encounter this bug before, I have tested on:
> 
> * A laptop with 1920x1080 and scale: 100%
> * Another laptop with 1920x1080 and scale: 125%
> * And a surface pro 4

a laptop with 1920x1080 and scale:125%
![image](https://user-images.githubusercontent.com/30150112/47796789-01b46a80-dd60-11e8-92f1-278bdfcb889d.png)

**Comment by LionelJouin** [comment]
Thank you, I managed to get this bug on another laptop, if you change your scale to 100%, you will not have this problem.

I will try to fix this problem as soon as possible.

**Comment by StrollStars** [comment]
@sickneet 感谢帮忙英文反馈问题。
@LionelJouin 
A desktop PC with 1920x1080 and scale:125%
64bit Win7

**Comment by LionelJouin** [comment]
Fixed in this version: [1.1.1](https://github.com/LionelJouin/PiP-Tool/releases/tag/1.1.1)
