### ISSUE TITLE
Program startup failed

### ISSUE THREAD

**Issue by StrollStars** [LionelJouin/PiP-Tool#5]
PiP-Tool Version: 1.1.1
System: Win 7 64bit
Screenshots: 
![](https://i.loli.net/2018/11/05/5be03d24b58f8.png)

**Comment by LionelJouin** [comment]
I see, to fix the issue #3, I used something only available on Windows 10. I will try to know if I can apply it for the previous version of Windows.

**Comment by bdd786** [comment]
Setup failed. 
![capture](https://user-images.githubusercontent.com/4282863/53910196-4ce9cd00-4021-11e9-9bd2-d31df8c33b3b.PNG)

**Comment by LionelJouin** [comment]
@bdd786 What is your windows 10 version ?

**Comment by bdd786** [comment]
Windows 10 Enterprise version
Bhavin
------------------------------------------------------------------------
*From:* Lionel Jouin [mailto:notifications@github.com]
*Sent:* Wednesday, March 6, 2019, 3:21 PM
*To:* LionelJouin/PiP-Tool
*Cc:* bdd786; Mention
*Subject:* [LionelJouin/PiP-Tool] Program startup failed (#5)

**Comment by LionelJouin** [comment]
I meant in the version, not the edition. You can find this information in Settings -> System -> About. For example, mine is 1809.

![alt text](https://i.imgur.com/1R6MCir.png)

**Comment by bdd786** [comment]
1803. See below

[image: image.png]

**Comment by Senpos** [comment]
Windows 7 x64, .NET 4.7.2, startapp failed

Prev. version (1.1) works just fine.

**Comment by LionelJouin** [comment]
I fixed the issue with the version 1.1.2 but I had to removed the DPI support on Windows 7 since I haven't found an equivalent of GetDpiForMonitor.

https://github.com/LionelJouin/PiP-Tool/releases/tag/1.1.2
